namespace Binance.Api.Futures;

/// <summary>
/// Funding rate information for Futures trading
/// </summary>
public record BinanceFuturesFundingRate
{
    /// <summary>
    /// The symbol the information is about
    /// </summary>
    public string Symbol { get; set; } = string.Empty;

    /// <summary>
    /// The finding rate for the given symbol and time
    /// </summary>
    public decimal FundingRate { get; set; }

    /// <summary>
    /// The time the funding rate is applied
    /// </summary>
    [JsonConverter(typeof(DateTimeConverter))]
    public DateTime FundingTime { get; set; }

    /// <summary>
    /// The mark price
    /// </summary>
    public decimal? MarkPrice { get; set; }

    /// <summary>
    /// Funding rate type. Binance currently publishes <c>Regular</c> for normal funding rates and
    /// <c>Special</c> for additional funding rates generated by stock dividends.
    /// </summary>
    [JsonProperty("rateType")]
    public string? RateType { get; set; }
}
