<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Binance.FIX.Api</PackageId>
		<Authors>Burak Öner</Authors>
		<Version>0.0.1</Version>
		<FileVersion>0.0.1</FileVersion>
		<PackageVersion>0.0.1</PackageVersion>
		<AssemblyVersion>0.0.1</AssemblyVersion>
		<Description>Development-stage Binance Spot FIX protocol client. This project is not yet a usable or supported API wrapper.</Description>
		<PackageTags>Binance;FIX;Spot;Trading;Cryptocurrency;Exchange;</PackageTags>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReleaseNotes>Please refer to changelog at Github https://github.com/burakoner/Binance.Api/blob/master/CHANGELOG.md</PackageReleaseNotes>
		<PackageIcon>Binance.png</PackageIcon>
		<PackageProjectUrl>https://github.com/burakoner/Binance.Api</PackageProjectUrl>
		<RepositoryUrl>https://github.com/burakoner/Binance.Api</RepositoryUrl>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<NeutralLanguage>en</NeutralLanguage>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Binance.png" Pack="true" PackagePath="\" />
		<None Include="../CHANGELOG.md" Pack="true" PackagePath="\" />
		<None Include="../README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" Version="25.4.0" />
    <PackageReference Include="QuickFIXn.Core" Version="1.14.1" />
  </ItemGroup>

</Project>
